package main

import (
	"go/ast"
	"go/token"
	"go/types"
	"strings"
)

func marshalName(typ *types.Named) string {
	return "_marshal_" + strings.ReplaceAll(strings.ReplaceAll(typ.Obj().Name(), "_", "__"), ".", "_")
}

func (c *constructor) imports(includeStdlib bool) *ast.GenDecl {
	var imports []ast.Spec

	if includeStdlib {
		imports = []ast.Spec{
			&ast.ImportSpec{
				Path: &ast.BasicLit{
					Kind:  token.STRING,
					Value: `"cmp"`,
				},
			},
			&ast.ImportSpec{
				Path: &ast.BasicLit{
					Kind:  token.STRING,
					Value: `"io"`,
				},
			},
		}
	}

	return &ast.GenDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  "// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT",
				},
			},
		},
		TokPos: c.newLine(),
		Tok:    token.IMPORT,
		Specs: append(imports, &ast.ImportSpec{
			Path: &ast.BasicLit{
				Kind:     token.STRING,
				Value:    `"vimagination.zapto.org/byteio"`,
				ValuePos: c.newLine(),
			},
		}),
	}
}

func (c *constructor) assignBinary(typeName, funcName, marshalName string) *ast.FuncDecl {
	comment := "// AppendBinary implements the encoding.BinaryAppender interface."

	if funcName != "AppendBinary" {
		comment = "// " + funcName + " appends the binary representation of itself to the end of b\n// (allocating a larger slice if necessary) and returns the updated slice."
	}

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  comment,
				},
			},
		},
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{
						ast.NewIdent("t"),
					},
					Type: &ast.UnaryExpr{
						Op: token.MUL,
						X:  ast.NewIdent(typeName),
					},
				},
			},
		},
		Name: &ast.Ident{
			Name: funcName,
		},
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("b"),
						},
						Type: &ast.ArrayType{
							Elt: ast.NewIdent("byte"),
						},
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: &ast.ArrayType{
							Elt: ast.NewIdent("byte"),
						},
					},
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("eb"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("byteio"),
								Sel: ast.NewIdent("MemLittleEndian"),
							},
							Args: []ast.Expr{
								ast.NewIdent("b"),
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("err"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: ast.NewIdent(marshalName),
							Args: []ast.Expr{
								ast.NewIdent("t"),
								&ast.UnaryExpr{
									Op: token.AND,
									X:  ast.NewIdent("eb"),
								},
							},
						},
					},
				},
				&ast.ReturnStmt{
					Return: c.newLine(),
					Results: []ast.Expr{
						ast.NewIdent("eb"),
						ast.NewIdent("err"),
					},
				},
			},
		},
	}
}

func (c *constructor) marshalBinary(typeName, funcName, marshalName string) *ast.FuncDecl {
	comment := "// MarshalBinary implements the encoding.BinaryMarshaler interface."

	if funcName != "MarshalBinary" {
		comment = "// " + funcName + " encodes the receiver into a binary form and returns the result."
	}

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  comment,
				},
			},
		},
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{
						ast.NewIdent("t"),
					},
					Type: &ast.UnaryExpr{
						Op: token.MUL,
						X:  ast.NewIdent(typeName),
					},
				},
			},
		},
		Name: &ast.Ident{
			Name: funcName,
		},
		Type: &ast.FuncType{
			Params: &ast.FieldList{},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: &ast.ArrayType{
							Elt: ast.NewIdent("byte"),
						},
					},
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("eb"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CompositeLit{
							Type: &ast.SelectorExpr{
								X:   ast.NewIdent("byteio"),
								Sel: ast.NewIdent("MemLittleEndian"),
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("err"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: ast.NewIdent(marshalName),
							Args: []ast.Expr{
								ast.NewIdent("t"),
								&ast.UnaryExpr{
									Op: token.AND,
									X:  ast.NewIdent("eb"),
								},
							},
						},
					},
				},
				&ast.ReturnStmt{
					Return: c.newLine(),
					Results: []ast.Expr{
						ast.NewIdent("eb"),
						ast.NewIdent("err"),
					},
				},
			},
		},
	}
}

func (c *constructor) writeTo(typeName, funcName, marshalName string) *ast.FuncDecl {
	comment := "// WriteTo implements the io.WriterTo interface."

	if funcName != "WriteTo" {
		comment = "// " + funcName + " writes data to w until there's no more data to write or when an error occurs.\n//\n// The return value n is the number of bytes written. Any error encountered during the write is also returned."
	}

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  comment,
				},
			},
		},
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{
						ast.NewIdent("t"),
					},
					Type: &ast.UnaryExpr{
						Op: token.MUL,
						X:  ast.NewIdent(typeName),
					},
				},
			},
		},
		Name: &ast.Ident{
			Name: funcName,
		},
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("w"),
						},
						Type: &ast.SelectorExpr{
							X:   ast.NewIdent("io"),
							Sel: ast.NewIdent("Writer"),
						},
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: ast.NewIdent("int64"),
					},
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.TypeSwitchStmt{
					Assign: &ast.AssignStmt{
						Lhs: []ast.Expr{
							ast.NewIdent("w"),
						},
						Tok: token.DEFINE,
						Rhs: []ast.Expr{
							&ast.TypeAssertExpr{
								X: ast.NewIdent("w"),
							},
						},
					},
					Body: &ast.BlockStmt{
						List: []ast.Stmt{
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("MemLittleEndian"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("len"),
												Args: []ast.Expr{
													&ast.UnaryExpr{
														Op: token.MUL,
														X:  ast.NewIdent("w"),
													},
												},
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("err"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent(marshalName),
												Args: []ast.Expr{
													ast.NewIdent("t"),
													ast.NewIdent("w"),
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("int64"),
												Args: []ast.Expr{
													&ast.BinaryExpr{
														X: &ast.CallExpr{
															Fun: ast.NewIdent("len"),
															Args: []ast.Expr{
																&ast.UnaryExpr{
																	Op: token.MUL,
																	X:  ast.NewIdent("w"),
																},
															},
														},
														Op: token.SUB,
														Y:  ast.NewIdent("l"),
													},
												},
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("MemBigEndian"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("len"),
												Args: []ast.Expr{
													&ast.UnaryExpr{
														Op: token.MUL,
														X:  ast.NewIdent("w"),
													},
												},
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("err"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent(marshalName),
												Args: []ast.Expr{
													ast.NewIdent("t"),
													ast.NewIdent("w"),
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("int64"),
												Args: []ast.Expr{
													&ast.BinaryExpr{
														X: &ast.CallExpr{
															Fun: ast.NewIdent("len"),
															Args: []ast.Expr{
																&ast.UnaryExpr{
																	Op: token.MUL,
																	X:  ast.NewIdent("w"),
																},
															},
														},
														Op: token.SUB,
														Y:  ast.NewIdent("l"),
													},
												},
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("StickyLittleEndianWriter"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("w"),
												Sel: ast.NewIdent("Count"),
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("w"),
												Sel: ast.NewIdent("Err"),
											},
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: &ast.SelectorExpr{
													X:   ast.NewIdent("cmp"),
													Sel: ast.NewIdent("Or"),
												},
												Args: []ast.Expr{
													&ast.SelectorExpr{
														X:   ast.NewIdent("w"),
														Sel: ast.NewIdent("Err"),
													},
													&ast.CallExpr{
														Fun: ast.NewIdent(marshalName),
														Args: []ast.Expr{
															ast.NewIdent("t"),
															ast.NewIdent("w"),
														},
													},
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.BinaryExpr{
												X: &ast.SelectorExpr{
													X:   ast.NewIdent("w"),
													Sel: ast.NewIdent("Count"),
												},
												Op: token.SUB,
												Y:  ast.NewIdent("l"),
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("StickyBigEndianWriter"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("w"),
												Sel: ast.NewIdent("Count"),
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("w"),
												Sel: ast.NewIdent("Err"),
											},
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: &ast.SelectorExpr{
													X:   ast.NewIdent("cmp"),
													Sel: ast.NewIdent("Or"),
												},
												Args: []ast.Expr{
													&ast.SelectorExpr{
														X:   ast.NewIdent("w"),
														Sel: ast.NewIdent("Err"),
													},
													&ast.CallExpr{
														Fun: ast.NewIdent(marshalName),
														Args: []ast.Expr{
															ast.NewIdent("t"),
															ast.NewIdent("w"),
														},
													},
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.BinaryExpr{
												X: &ast.SelectorExpr{
													X:   ast.NewIdent("w"),
													Sel: ast.NewIdent("Count"),
												},
												Op: token.SUB,
												Y:  ast.NewIdent("l"),
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						&ast.Ident{
							NamePos: c.newLine(),
							Name:    "sw",
						},
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CompositeLit{
							Type: &ast.SelectorExpr{
								X:   ast.NewIdent("byteio"),
								Sel: ast.NewIdent("StickyLittleEndianWriter"),
							},
							Elts: []ast.Expr{
								&ast.KeyValueExpr{
									Key:   ast.NewIdent("Writer"),
									Value: ast.NewIdent("w"),
								},
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("err"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("cmp"),
								Sel: ast.NewIdent("Or"),
							},
							Args: []ast.Expr{
								&ast.CallExpr{
									Fun: ast.NewIdent(marshalName),
									Args: []ast.Expr{
										ast.NewIdent("t"),
										&ast.UnaryExpr{
											Op: token.AND,
											X:  ast.NewIdent("sw"),
										},
									},
								},
								&ast.SelectorExpr{
									X:   ast.NewIdent("sw"),
									Sel: ast.NewIdent("Err"),
								},
							},
						},
					},
				},
				&ast.ReturnStmt{
					Return: c.newLine(),
					Results: []ast.Expr{
						&ast.SelectorExpr{
							X:   ast.NewIdent("sw"),
							Sel: ast.NewIdent("Count"),
						},
						ast.NewIdent("err"),
					},
				},
			},
		},
	}
}

func (c *constructor) addStatement(stmt ast.Stmt) {
	c.statements = append(c.statements, stmt)
}

func (c *constructor) writeType(name ast.Expr, typ types.Type) {
	switch t := typ.Underlying().(type) {
	case *types.Struct:
		c.writeStruct(name, t)
	case *types.Array:
		c.writeArray(name, t)
	case *types.Slice:
		c.writeSlice(name, t)
	case *types.Map:
		c.writeMap(name, t)
	case *types.Pointer:
		c.writePointer(name, t)
	case *types.Basic:
		c.writeBasic(name, t)
	}
}

func (c *constructor) writeStruct(name ast.Expr, t *types.Struct) {
	for field := range t.Fields() {
		if !field.Exported() {
			continue
		}

		c.writeType(&ast.SelectorExpr{
			X:   name,
			Sel: ast.NewIdent(field.Name()),
		}, field.Type())
	}
}

func (c *constructor) addWriter(method string, name ast.Expr) {
	c.addCall(&ast.SelectorExpr{
		X:   ast.NewIdent("w"),
		Sel: ast.NewIdent(method),
	}, name)
}

func (c *constructor) subConstructor() *constructor {
	return &constructor{
		pkg:   c.pkg,
		pos:   c.pos,
		types: c.types,
	}
}

func (c *constructor) writeArray(name ast.Expr, t *types.Array) {
	d := c.subConstructor()

	d.writeType(ast.NewIdent("e"), t.Elem())
	c.addStatement(&ast.RangeStmt{
		For:   c.newLine(),
		Key:   ast.NewIdent("_"),
		Value: ast.NewIdent("e"),
		Tok:   token.DEFINE,
		X:     name,
		Body: &ast.BlockStmt{
			List: d.statements,
		},
	})
}

func (c *constructor) writeSlice(name ast.Expr, t *types.Slice) {
	c.addWriter("WriteUintX", &ast.CallExpr{
		Fun: ast.NewIdent("uint64"),
		Args: []ast.Expr{
			&ast.CallExpr{
				Fun:  ast.NewIdent("len"),
				Args: []ast.Expr{name},
			},
		},
	})
	c.writeArray(name, types.NewArray(t.Elem(), 0))
}

func (c *constructor) writeMap(name ast.Expr, t *types.Map) {
	d := c.subConstructor()

	d.writeType(ast.NewIdent("k"), t.Key())
	d.writeType(ast.NewIdent("v"), t.Elem())
	c.addWriter("WriteUintX", &ast.CallExpr{
		Fun: ast.NewIdent("uint64"),
		Args: []ast.Expr{
			&ast.CallExpr{
				Fun:  ast.NewIdent("len"),
				Args: []ast.Expr{name},
			},
		},
	})
	c.addStatement(&ast.RangeStmt{
		For:   c.newLine(),
		Key:   ast.NewIdent("k"),
		Value: ast.NewIdent("v"),
		Tok:   token.DEFINE,
		X:     name,
		Body: &ast.BlockStmt{
			List: d.statements,
		},
	})
}

func (c *constructor) writePointer(name ast.Expr, t *types.Pointer) {
	d := c.subConstructor()

	d.writeType(name, t.Elem())
	c.addStatement(&ast.ExprStmt{
		X: &ast.CallExpr{
			Fun: &ast.SelectorExpr{
				X:   ast.NewIdent("w"),
				Sel: ast.NewIdent("WriteBool"),
			},
			Args: []ast.Expr{
				&ast.BinaryExpr{
					X:  name,
					Op: token.NEQ,
					Y:  ast.NewIdent("nil"),
				},
			},
		},
	})
	c.addStatement(&ast.IfStmt{
		Cond: &ast.BinaryExpr{
			X:  name,
			Op: token.NEQ,
			Y:  ast.NewIdent("nil"),
		},
		Body: &ast.BlockStmt{
			List: d.statements,
		},
	})
}

func (c *constructor) writeBasic(name ast.Expr, t *types.Basic) {
	switch t.Kind() {
	case types.Bool:
		c.addWriter("WriteBool", name)
	case types.Int:
		c.addWriter("WriteInt64", name)
	case types.Int8:
		c.addWriter("WriteInt8", name)
	case types.Int16:
		c.addWriter("WriteInt16", name)
	case types.Int32:
		c.addWriter("WriteInt32", name)
	case types.Int64:
		c.addWriter("WriteInt64", name)
	case types.Uint:
		c.addWriter("WriteUint64", name)
	case types.Uint8:
		c.addWriter("WriteUint8", name)
	case types.Uint16:
		c.addWriter("WriteUint16", name)
	case types.Uint32:
		c.addWriter("WriteUint32", name)
	case types.Uint64, types.Uintptr:
		c.addWriter("WriteUint64", name)
	case types.Float32:
		c.addWriter("WriteFloat32", name)
	case types.Float64:
		c.addWriter("WriteFloat64", name)
	case types.Complex64:
		c.addWriter("WriteFloat32", &ast.CallExpr{
			Fun:  ast.NewIdent("real"),
			Args: []ast.Expr{name},
		})
		c.addWriter("WriteFloat32", &ast.CallExpr{
			Fun:  ast.NewIdent("imag"),
			Args: []ast.Expr{name},
		})
	case types.Complex128:
		c.addWriter("WriteFloat64", &ast.CallExpr{
			Fun:  ast.NewIdent("real"),
			Args: []ast.Expr{name},
		})
		c.addWriter("WriteFloat64", &ast.CallExpr{
			Fun:  ast.NewIdent("imag"),
			Args: []ast.Expr{name},
		})
	case types.String:
		c.addWriter("WriteStringX", name)
	}
}

func deref(typ types.Type) types.Type {
	if ptr, ok := typ.(*types.Pointer); ok {
		return ptr.Elem()
	}

	return typ
}

func (c *constructor) marshalFunc(typ *types.Named) *ast.FuncDecl {
	typeName := typ.Obj().Name()
	marshalName := marshalName(typ)
	c.statements = nil

	c.writeType(ast.NewIdent("t"), deref(typ.Underlying()))

	return &ast.FuncDecl{
		Name: &ast.Ident{
			Name: marshalName,
		},
		Type: &ast.FuncType{
			Func: c.newLine(),
			TypeParams: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("W"),
						},
						Type: &ast.SelectorExpr{
							X:   ast.NewIdent("byteio"),
							Sel: ast.NewIdent("StickyWriter"),
						},
					},
				},
			},
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("t"),
						},
						Type: &ast.UnaryExpr{
							Op: token.MUL,
							X:  ast.NewIdent(typeName),
						},
					},
					{
						Names: []*ast.Ident{
							ast.NewIdent("w"),
						},
						Type: ast.NewIdent("W"),
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: append(c.statements, &ast.ReturnStmt{
				Return: c.newLine(),
				Results: []ast.Expr{
					ast.NewIdent("nil"),
				},
			}),
		},
	}
}
