package main

import (
	"go/ast"
	"go/format"
	"go/token"
	"io"
)

func constructFile(w io.Writer, pkg string) {
	fset := token.NewFileSet()
	lines := []int{0}
	newLine := func() token.Pos {
		l := len(lines)
		lines = append(lines, len(lines), len(lines)+1)

		return token.Pos(l + 1)
	}
	file := &ast.File{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: newLine(),
					Text:  "//go:generate go run vimagination.zapto.org/marshal@latest --opts",
				},
			},
		},
		Name:    ast.NewIdent(pkg),
		Package: newLine(),
		Decls: []ast.Decl{
			&ast.GenDecl{
				Doc: &ast.CommentGroup{
					List: []*ast.Comment{
						{
							Slash: newLine(),
							Text:  "// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT",
						},
					},
				},
				TokPos: newLine(),
				Tok:    token.IMPORT,
				Specs: []ast.Spec{
					&ast.ImportSpec{
						Path: &ast.BasicLit{
							Kind:  token.STRING,
							Value: `"io"`,
						},
					},
					&ast.ImportSpec{
						Path: &ast.BasicLit{
							Kind:     token.STRING,
							Value:    `"vimagination.zapto.org/byteio"`,
							ValuePos: newLine(),
						},
					},
				},
			},
		},
	}

	wsfile := fset.AddFile("out.go", 1, len(lines))

	wsfile.SetLines(lines)
	format.Node(w, fset, file)
}
