package main

import (
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"io"
	"strconv"
	"strings"
)

type pos []int

func (p *pos) newLine() token.Pos {
	l := len(*p)
	*p = append(*p, len(*p), len(*p)+1)

	return token.Pos(l + 1)
}

type constructor struct {
	pos
}

func constructFile(w io.Writer, pkg string, assigner, marshaler, unmarshaler, writer, reader string, opts []string, types ...*types.Named) error {
	c := constructor{pos: pos{0}}
	file := &ast.File{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  "//go:generate go run vimagination.zapto.org/marshal@latest " + encodeOpts(opts),
				},
			},
		},
		Name:    ast.NewIdent(pkg),
		Package: c.newLine(),
		Decls:   c.buildDecls(assigner, marshaler, unmarshaler, writer, reader, types),
	}
	fset := token.NewFileSet()
	wsfile := fset.AddFile("out.go", 1, len(c.pos))

	wsfile.SetLines(c.pos)

	return format.Node(w, fset, file)
}

func encodeOpts(opts []string) string {
	var buf []byte

	for n, opt := range opts {
		if n > 0 {
			buf = append(buf, ' ')
		}

		if strings.Contains(opt, " ") {
			buf = strconv.AppendQuote(buf, opt)
		} else {
			buf = append(buf, opt...)
		}
	}

	return string(buf)
}

func (c *constructor) buildDecls(assigner, marshaler, unmarshaler, writer, reader string, types []*types.Named) []ast.Decl {
	decls := []ast.Decl{
		c.imports(writer != "" || reader != ""),
	}

	for _, typ := range types {
		typeName := typ.Obj().Name()
		marshalName := marshalName(typ)
		unmarshalName := unmarshalName(typ)

		if assigner != "" {
			decls = append(decls, c.assignBinary(typeName, assigner, marshalName))
		}

		if marshaler != "" {
			decls = append(decls, c.marshalBinary(typeName, marshaler, marshalName))
		}

		if writer != "" {
			decls = append(decls, c.writeTo(typeName, writer, marshalName))
		}

		if unmarshaler != "" {
			decls = append(decls, c.unmarshalBinary(typeName, unmarshaler, unmarshalName))
		}

		if reader != "" {
			decls = append(decls, c.readFrom(typeName, reader, unmarshalName))
		}
	}

	for _, typ := range types {
		if assigner != "" || marshaler != "" || writer != "" {
			decls = append(decls, c.marshalFunc(typ))
		}

		if unmarshaler != "" || reader != "" {
			decls = append(decls, c.unmarshalFunc(typ))
		}
	}

	return decls
}

func marshalName(typ *types.Named) string {
	return "_marshal·" + strings.ReplaceAll(strings.ReplaceAll(typ.Obj().Name(), "·", "··"), ".", "·")
}

func unmarshalName(typ *types.Named) string {
	return "_unmarshal·" + strings.ReplaceAll(strings.ReplaceAll(typ.Obj().Name(), "·", "··"), ".", "·")
}

func (c *constructor) imports(includeStdlib bool) *ast.GenDecl {
	var imports []ast.Spec

	if includeStdlib {
		imports = []ast.Spec{
			&ast.ImportSpec{
				Path: &ast.BasicLit{
					Kind:  token.STRING,
					Value: `"cmp"`,
				},
			},
			&ast.ImportSpec{
				Path: &ast.BasicLit{
					Kind:  token.STRING,
					Value: `"io"`,
				},
			},
		}
	}

	return &ast.GenDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  "// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT",
				},
			},
		},
		TokPos: c.newLine(),
		Tok:    token.IMPORT,
		Specs: append(imports, &ast.ImportSpec{
			Path: &ast.BasicLit{
				Kind:     token.STRING,
				Value:    `"vimagination.zapto.org/byteio"`,
				ValuePos: c.newLine(),
			},
		}),
	}
}

func (c *constructor) assignBinary(typeName, funcName, marshalName string) *ast.FuncDecl {
	comment := "// AppendBinary implements the encoding.BinaryAppender interface."

	if funcName != "AppendBinary" {
		comment = "// " + funcName + " appends the binary representation of itself to the end of b\n// (allocating a larger slice if necessary) and returns the updated slice."
	}

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  comment,
				},
			},
		},
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{
						ast.NewIdent("t"),
					},
					Type: &ast.UnaryExpr{
						Op: token.MUL,
						X:  ast.NewIdent(typeName),
					},
				},
			},
		},
		Name: &ast.Ident{
			Name: funcName,
		},
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("b"),
						},
						Type: &ast.ArrayType{
							Elt: ast.NewIdent("byte"),
						},
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: &ast.ArrayType{
							Elt: ast.NewIdent("byte"),
						},
					},
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("eb"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("byteio"),
								Sel: ast.NewIdent("MemLittleEndian"),
							},
							Args: []ast.Expr{
								ast.NewIdent("b"),
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("err"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: ast.NewIdent(marshalName),
							Args: []ast.Expr{
								ast.NewIdent("t"),
								&ast.UnaryExpr{
									Op: token.AND,
									X:  ast.NewIdent("eb"),
								},
							},
						},
					},
				},
				&ast.ReturnStmt{
					Return: c.newLine(),
					Results: []ast.Expr{
						ast.NewIdent("eb"),
						ast.NewIdent("err"),
					},
				},
			},
		},
	}
}

func (c *constructor) marshalBinary(typeName, funcName, marshalName string) *ast.FuncDecl {
	comment := "// MarshalBinary implements the encoding.BinaryMarshaler interface."

	if funcName != "MarshalBinary" {
		comment = "// " + funcName + " encodes the receiver into a binary form and returns the result."
	}

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  comment,
				},
			},
		},
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{
						ast.NewIdent("t"),
					},
					Type: &ast.UnaryExpr{
						Op: token.MUL,
						X:  ast.NewIdent(typeName),
					},
				},
			},
		},
		Name: &ast.Ident{
			Name: funcName,
		},
		Type: &ast.FuncType{
			Params: &ast.FieldList{},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: &ast.ArrayType{
							Elt: ast.NewIdent("byte"),
						},
					},
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("eb"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CompositeLit{
							Type: &ast.SelectorExpr{
								X:   ast.NewIdent("byteio"),
								Sel: ast.NewIdent("MemLittleEndian"),
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("err"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: ast.NewIdent(marshalName),
							Args: []ast.Expr{
								ast.NewIdent("t"),
								&ast.UnaryExpr{
									Op: token.AND,
									X:  ast.NewIdent("eb"),
								},
							},
						},
					},
				},
				&ast.ReturnStmt{
					Return: c.newLine(),
					Results: []ast.Expr{
						ast.NewIdent("eb"),
						ast.NewIdent("err"),
					},
				},
			},
		},
	}
}

func (c *constructor) writeTo(typeName, funcName, marshalName string) *ast.FuncDecl {
	comment := "// WriteTo implements the io.WriterTo interface."

	if funcName != "WriteTo" {
		comment = "// " + funcName + " writes data to w until there's no more data to write or when an error occurs.\n//\n// The return value n is the number of bytes written. Any error encountered during the write is also returned."
	}

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  comment,
				},
			},
		},
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{
						ast.NewIdent("t"),
					},
					Type: &ast.UnaryExpr{
						Op: token.MUL,
						X:  ast.NewIdent(typeName),
					},
				},
			},
		},
		Name: &ast.Ident{
			Name: funcName,
		},
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("w"),
						},
						Type: &ast.SelectorExpr{
							X:   ast.NewIdent("io"),
							Sel: ast.NewIdent("Writer"),
						},
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: ast.NewIdent("int64"),
					},
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.TypeSwitchStmt{
					Assign: &ast.AssignStmt{
						Lhs: []ast.Expr{
							ast.NewIdent("w"),
						},
						Tok: token.DEFINE,
						Rhs: []ast.Expr{
							&ast.TypeAssertExpr{
								X: ast.NewIdent("w"),
							},
						},
					},
					Body: &ast.BlockStmt{
						List: []ast.Stmt{
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("MemLittleEndian"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("len"),
												Args: []ast.Expr{
													&ast.UnaryExpr{
														Op: token.MUL,
														X:  ast.NewIdent("w"),
													},
												},
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("err"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent(marshalName),
												Args: []ast.Expr{
													ast.NewIdent("t"),
													ast.NewIdent("w"),
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("int64"),
												Args: []ast.Expr{
													&ast.BinaryExpr{
														X: &ast.CallExpr{
															Fun: ast.NewIdent("len"),
															Args: []ast.Expr{
																&ast.UnaryExpr{
																	Op: token.MUL,
																	X:  ast.NewIdent("w"),
																},
															},
														},
														Op: token.SUB,
														Y:  ast.NewIdent("l"),
													},
												},
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("MemBigEndian"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("len"),
												Args: []ast.Expr{
													&ast.UnaryExpr{
														Op: token.MUL,
														X:  ast.NewIdent("w"),
													},
												},
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("err"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent(marshalName),
												Args: []ast.Expr{
													ast.NewIdent("t"),
													ast.NewIdent("w"),
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("int64"),
												Args: []ast.Expr{
													&ast.BinaryExpr{
														X: &ast.CallExpr{
															Fun: ast.NewIdent("len"),
															Args: []ast.Expr{
																&ast.UnaryExpr{
																	Op: token.MUL,
																	X:  ast.NewIdent("w"),
																},
															},
														},
														Op: token.SUB,
														Y:  ast.NewIdent("l"),
													},
												},
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("StickyLittleEndianWriter"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("w"),
												Sel: ast.NewIdent("Count"),
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("w"),
												Sel: ast.NewIdent("Err"),
											},
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: &ast.SelectorExpr{
													X:   ast.NewIdent("cmp"),
													Sel: ast.NewIdent("Or"),
												},
												Args: []ast.Expr{
													&ast.SelectorExpr{
														X:   ast.NewIdent("w"),
														Sel: ast.NewIdent("Err"),
													},
													&ast.CallExpr{
														Fun: ast.NewIdent(marshalName),
														Args: []ast.Expr{
															ast.NewIdent("t"),
															ast.NewIdent("w"),
														},
													},
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.BinaryExpr{
												X: &ast.SelectorExpr{
													X:   ast.NewIdent("w"),
													Sel: ast.NewIdent("Count"),
												},
												Op: token.SUB,
												Y:  ast.NewIdent("l"),
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("StickyBigEndianWriter"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("w"),
												Sel: ast.NewIdent("Count"),
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("w"),
												Sel: ast.NewIdent("Err"),
											},
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: &ast.SelectorExpr{
													X:   ast.NewIdent("cmp"),
													Sel: ast.NewIdent("Or"),
												},
												Args: []ast.Expr{
													&ast.SelectorExpr{
														X:   ast.NewIdent("w"),
														Sel: ast.NewIdent("Err"),
													},
													&ast.CallExpr{
														Fun: ast.NewIdent(marshalName),
														Args: []ast.Expr{
															ast.NewIdent("t"),
															ast.NewIdent("w"),
														},
													},
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.BinaryExpr{
												X: &ast.SelectorExpr{
													X:   ast.NewIdent("w"),
													Sel: ast.NewIdent("Count"),
												},
												Op: token.SUB,
												Y:  ast.NewIdent("l"),
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						&ast.Ident{
							NamePos: c.newLine(),
							Name:    "sw",
						},
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CompositeLit{
							Type: &ast.SelectorExpr{
								X:   ast.NewIdent("byteio"),
								Sel: ast.NewIdent("StickyLittleEndianWriter"),
							},
							Elts: []ast.Expr{
								&ast.KeyValueExpr{
									Key:   ast.NewIdent("Writer"),
									Value: ast.NewIdent("w"),
								},
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("err"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("cmp"),
								Sel: ast.NewIdent("Or"),
							},
							Args: []ast.Expr{
								&ast.CallExpr{
									Fun: ast.NewIdent(marshalName),
									Args: []ast.Expr{
										ast.NewIdent("t"),
										&ast.UnaryExpr{
											Op: token.AND,
											X:  ast.NewIdent("sw"),
										},
									},
								},
								&ast.SelectorExpr{
									X:   ast.NewIdent("sw"),
									Sel: ast.NewIdent("Err"),
								},
							},
						},
					},
				},
				&ast.ReturnStmt{
					Return: c.newLine(),
					Results: []ast.Expr{
						&ast.SelectorExpr{
							X:   ast.NewIdent("sw"),
							Sel: ast.NewIdent("Count"),
						},
						ast.NewIdent("err"),
					},
				},
			},
		},
	}
}

func (c *constructor) marshalFunc(typ *types.Named) *ast.FuncDecl {
	typeName := typ.Obj().Name()
	marshalName := marshalName(typ)

	return &ast.FuncDecl{
		Name: &ast.Ident{
			Name: marshalName,
		},
		Type: &ast.FuncType{
			Func: c.newLine(),
			TypeParams: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("W"),
						},
						Type: &ast.SelectorExpr{
							X:   ast.NewIdent("byteio"),
							Sel: ast.NewIdent("StickyWriter"),
						},
					},
				},
			},
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("t"),
						},
						Type: &ast.UnaryExpr{
							Op: token.MUL,
							X:  ast.NewIdent(typeName),
						},
					},
					{
						Names: []*ast.Ident{
							ast.NewIdent("w"),
						},
						Type: ast.NewIdent("W"),
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{
						ast.NewIdent("nil"),
					},
				},
			},
		},
	}
}

func (c *constructor) unmarshalBinary(typeName, funcName, unmarshalName string) *ast.FuncDecl {
	comment := "// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface."

	if funcName != "UnmarshalBinary" {
		comment = "// " + funcName + " decodes the receiver from the binary form."
	}

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  comment,
				},
			},
		},
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{
						ast.NewIdent("t"),
					},
					Type: &ast.UnaryExpr{
						Op: token.MUL,
						X:  ast.NewIdent(typeName),
					},
				},
			},
		},
		Name: &ast.Ident{
			Name: funcName,
		},
		Type: &ast.FuncType{
			Params: &ast.FieldList{},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("eb"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CompositeLit{
							Type: &ast.SelectorExpr{
								X:   ast.NewIdent("byteio"),
								Sel: ast.NewIdent("MemLittleEndian"),
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("err"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: ast.NewIdent(unmarshalName),
							Args: []ast.Expr{
								ast.NewIdent("t"),
								&ast.UnaryExpr{
									Op: token.AND,
									X:  ast.NewIdent("eb"),
								},
							},
						},
					},
				},
				&ast.ReturnStmt{
					Return: c.newLine(),
					Results: []ast.Expr{
						ast.NewIdent("err"),
					},
				},
			},
		},
	}
}

func (c *constructor) readFrom(typeName, funcName, unmarshalName string) *ast.FuncDecl {
	comment := "// ReadFrom implements the io.ReaderFrom interface."

	if funcName != "ReadFrom" {
		comment = "// " + funcName + " reads data from r until the type is fully decoded.\n//\n// The return value n is the number of bytes read. Any error encountered during the read is also returned."
	}

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Slash: c.newLine(),
					Text:  comment,
				},
			},
		},
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{
						ast.NewIdent("t"),
					},
					Type: &ast.UnaryExpr{
						Op: token.MUL,
						X:  ast.NewIdent(typeName),
					},
				},
			},
		},
		Name: &ast.Ident{
			Name: funcName,
		},
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("r"),
						},
						Type: &ast.SelectorExpr{
							X:   ast.NewIdent("io"),
							Sel: ast.NewIdent("Reader"),
						},
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: ast.NewIdent("int64"),
					},
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.TypeSwitchStmt{
					Assign: &ast.AssignStmt{
						Lhs: []ast.Expr{
							ast.NewIdent("r"),
						},
						Tok: token.DEFINE,
						Rhs: []ast.Expr{
							&ast.TypeAssertExpr{
								X: ast.NewIdent("r"),
							},
						},
					},
					Body: &ast.BlockStmt{
						List: []ast.Stmt{
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("MemLittleEndian"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("len"),
												Args: []ast.Expr{
													&ast.UnaryExpr{
														Op: token.MUL,
														X:  ast.NewIdent("r"),
													},
												},
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("err"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent(unmarshalName),
												Args: []ast.Expr{
													ast.NewIdent("t"),
													ast.NewIdent("r"),
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("int64"),
												Args: []ast.Expr{
													&ast.BinaryExpr{
														X: &ast.CallExpr{
															Fun: ast.NewIdent("len"),
															Args: []ast.Expr{
																&ast.UnaryExpr{
																	Op: token.MUL,
																	X:  ast.NewIdent("r"),
																},
															},
														},
														Op: token.SUB,
														Y:  ast.NewIdent("l"),
													},
												},
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("MemBigEndian"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("len"),
												Args: []ast.Expr{
													&ast.UnaryExpr{
														Op: token.MUL,
														X:  ast.NewIdent("r"),
													},
												},
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("err"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent(unmarshalName),
												Args: []ast.Expr{
													ast.NewIdent("t"),
													ast.NewIdent("r"),
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.CallExpr{
												Fun: ast.NewIdent("int64"),
												Args: []ast.Expr{
													&ast.BinaryExpr{
														X: &ast.CallExpr{
															Fun: ast.NewIdent("len"),
															Args: []ast.Expr{
																&ast.UnaryExpr{
																	Op: token.MUL,
																	X:  ast.NewIdent("r"),
																},
															},
														},
														Op: token.SUB,
														Y:  ast.NewIdent("l"),
													},
												},
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("StickyLittleEndianReader"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("r"),
												Sel: ast.NewIdent("Count"),
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("r"),
												Sel: ast.NewIdent("Err"),
											},
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: &ast.SelectorExpr{
													X:   ast.NewIdent("cmp"),
													Sel: ast.NewIdent("Or"),
												},
												Args: []ast.Expr{
													&ast.SelectorExpr{
														X:   ast.NewIdent("r"),
														Sel: ast.NewIdent("Err"),
													},
													&ast.CallExpr{
														Fun: ast.NewIdent(unmarshalName),
														Args: []ast.Expr{
															ast.NewIdent("t"),
															ast.NewIdent("r"),
														},
													},
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.BinaryExpr{
												X: &ast.SelectorExpr{
													X:   ast.NewIdent("r"),
													Sel: ast.NewIdent("Count"),
												},
												Op: token.SUB,
												Y:  ast.NewIdent("l"),
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
							&ast.CaseClause{
								List: []ast.Expr{
									&ast.UnaryExpr{
										Op: token.MUL,
										X: &ast.SelectorExpr{
											X:   ast.NewIdent("byteio"),
											Sel: ast.NewIdent("StickyBigEndianReader"),
										},
									},
								},
								Body: []ast.Stmt{
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											ast.NewIdent("l"),
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("r"),
												Sel: ast.NewIdent("Count"),
											},
										},
									},
									&ast.AssignStmt{
										Lhs: []ast.Expr{
											&ast.SelectorExpr{
												X:   ast.NewIdent("r"),
												Sel: ast.NewIdent("Err"),
											},
										},
										Tok: token.DEFINE,
										Rhs: []ast.Expr{
											&ast.CallExpr{
												Fun: &ast.SelectorExpr{
													X:   ast.NewIdent("cmp"),
													Sel: ast.NewIdent("Or"),
												},
												Args: []ast.Expr{
													&ast.SelectorExpr{
														X:   ast.NewIdent("r"),
														Sel: ast.NewIdent("Err"),
													},
													&ast.CallExpr{
														Fun: ast.NewIdent(unmarshalName),
														Args: []ast.Expr{
															ast.NewIdent("t"),
															ast.NewIdent("r"),
														},
													},
												},
											},
										},
									},
									&ast.ReturnStmt{
										Return: c.newLine(),
										Results: []ast.Expr{
											&ast.BinaryExpr{
												X: &ast.SelectorExpr{
													X:   ast.NewIdent("r"),
													Sel: ast.NewIdent("Count"),
												},
												Op: token.SUB,
												Y:  ast.NewIdent("l"),
											},
											ast.NewIdent("err"),
										},
									},
								},
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						&ast.Ident{
							NamePos: c.newLine(),
							Name:    "sr",
						},
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CompositeLit{
							Type: &ast.SelectorExpr{
								X:   ast.NewIdent("byteio"),
								Sel: ast.NewIdent("StickyLittleEndianReader"),
							},
							Elts: []ast.Expr{
								&ast.KeyValueExpr{
									Key:   ast.NewIdent("Reader"),
									Value: ast.NewIdent("r"),
								},
							},
						},
					},
				},
				&ast.AssignStmt{
					Lhs: []ast.Expr{
						ast.NewIdent("err"),
					},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("cmp"),
								Sel: ast.NewIdent("Or"),
							},
							Args: []ast.Expr{
								&ast.CallExpr{
									Fun: ast.NewIdent(unmarshalName),
									Args: []ast.Expr{
										ast.NewIdent("t"),
										&ast.UnaryExpr{
											Op: token.AND,
											X:  ast.NewIdent("sr"),
										},
									},
								},
								&ast.SelectorExpr{
									X:   ast.NewIdent("sr"),
									Sel: ast.NewIdent("Err"),
								},
							},
						},
					},
				},
				&ast.ReturnStmt{
					Return: c.newLine(),
					Results: []ast.Expr{
						&ast.SelectorExpr{
							X:   ast.NewIdent("sr"),
							Sel: ast.NewIdent("Count"),
						},
						ast.NewIdent("err"),
					},
				},
			},
		},
	}
}

func (c *constructor) unmarshalFunc(typ *types.Named) *ast.FuncDecl {
	typeName := typ.Obj().Name()
	unmarshalName := unmarshalName(typ)

	return &ast.FuncDecl{
		Name: &ast.Ident{
			Name: unmarshalName,
		},
		Type: &ast.FuncType{
			Func: c.newLine(),
			TypeParams: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("R"),
						},
						Type: &ast.SelectorExpr{
							X:   ast.NewIdent("byteio"),
							Sel: ast.NewIdent("StickyReader"),
						},
					},
				},
			},
			Params: &ast.FieldList{
				List: []*ast.Field{
					{
						Names: []*ast.Ident{
							ast.NewIdent("t"),
						},
						Type: &ast.UnaryExpr{
							Op: token.MUL,
							X:  ast.NewIdent(typeName),
						},
					},
					{
						Names: []*ast.Ident{
							ast.NewIdent("r"),
						},
						Type: ast.NewIdent("R"),
					},
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: ast.NewIdent("error"),
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{
						ast.NewIdent("nil"),
					},
				},
			},
		},
	}
}
